const sortedItems = [
    { index: 1,  text: 'Number of residents' },
    { index: 2,  text: 'Water purification methods' },
    { index: 3,  text: 'Consumption of bottled water' },
    { index: 4,  text: 'Use of low-flow toilets' },
    { index: 5,  text: 'Presence of desert plants' },
    { index: 6,  text: 'Cleaning frequency' },
    { index: 7,  text: 'Plastic recycling habits' },
    { index: 8,  text: 'Paper recycling habits' },
    { index: 9,  text: 'Clothes donation/reuse' },
    { index: 10, text: 'Primary diet' },
    { index: 11, text: 'Daily water consumption per person' },
    { index: 12, text: 'Frequency of bottled water consumption' },
    { index: 13, text: 'Shower duration' },
    { index: 14, text: 'Bath frequency' },
    { index: 15, text: 'Use of low-flow shower-heads' },
    { index: 16, text: 'Tap running duration and type' },
    { index: 17, text: 'Dishwashing routine' },
    { index: 18, text: 'Water usage for dishwashing' },
    { index: 19, text: 'Laundry routine' },
    { index: 20, text: 'Laundry load size' },
    { index: 21, text: 'Water usage for plant watering' },
    { index: 22, text: 'Number of vehicles owned' },
    { index: 23, text: 'Vehicle washing routine' },
    { index: 24, text: 'Frequency of vehicle washing' },
    { index: 25, text: 'Meat consumption frequency' },
    { index: 26, text: 'Dairy product consumption frequency' },
    { index: 27, text: 'Beverage consumption frequency' },
    { index: 28, text: 'Number of pets owned' },
    { index: 29, text: 'Pet washing frequency' },
  ];

module.exports = {sortedItems}