const items = [
  { title: "bag", waterFootprint: 0.211 },
  { title: "Plastic bag", waterFootprint: 0.211 },
  { title: "Pen", waterFootprint: 0.327 },
  { title: "Bottle", waterFootprint: 0.01 },
  { title: "Food", waterFootprint: 0.976 },
  { title: "Coffee", waterFootprint: 1.4 },
  { title: "Black Tea", waterFootprint: 0.034 },
  { title: "Disposable Diaper", waterFootprint: 0.545 },
  { title: "Wet Food for Pets", waterFootprint: 6.92 },
  { title: "Cotton for Jeans", waterFootprint: 3.785 },
  { title: "Banana", waterFootprint: 0.395 },
  { title: "Polyester Shirt", waterFootprint: 0.35 },
  { title: "Cotton Shirt", waterFootprint: 2.495 },
  { title: "Ketchup", waterFootprint: 0.015 },
  { title: "Rubber Tires", waterFootprint: 3.92 },
  { title: "Margherita Pizza", waterFootprint: 1.26 },
  { title: "Whisky", waterFootprint: 1.62 },
  { title: "Pasta Noodle", waterFootprint: 0.0019 },
  { title: "Paper", waterFootprint: 1.5 },
  { title: "device", waterFootprint: 0.908 },
  { title: "electronic", waterFootprint: 0.908 },
  { title: "phone", waterFootprint: 0.908 },
  { title: "Beef", waterFootprint: 7.7 },
  { title: "Nuts", waterFootprint: 9 },
  { title: "Pulses", waterFootprint: 4 },
  { title: "Vegetables", waterFootprint: 0.3 },
  { title: "Fruits", waterFootprint: 0.9 },
  { title: "Chocolate", waterFootprint: 6 },
  { title: "Rice", waterFootprint: 0.762 },
  { title: "Bread", waterFootprint: 0.454 },
  { title: "Cheese", waterFootprint: 0.723 },
  { title: "Turkey", waterFootprint: 0.887 },
  { title: "Potato Chips", waterFootprint: 0.023 },
  { title: "Soda", waterFootprint: 0.087 },
  { title: "Wine", waterFootprint: 0.129 },
  { title: "Beer", waterFootprint: 0.036 },
  { title: "Sugar", waterFootprint: 0.337 },
  { title: "Corn", waterFootprint: 0.204 },
  { title: "Eggs", waterFootprint: 0.201 },
  { title: "Chicken", waterFootprint: 0.887 },
  { title: "Pork", waterFootprint: 1.09 },
  { title: "Apples", waterFootprint: 0.157 },
  { title: "Oranges", waterFootprint: 0.104 },
  { title: "Grapes", waterFootprint: 0.045 },
  { title: "Tomatoes", waterFootprint: 0.042 },
  { title: "Lettuce", waterFootprint: 0.028 },
  { title: "Carrots", waterFootprint: 0.062 },
  { title: "Wheat", waterFootprint: 1.83 },
  { title: "Cotton", waterFootprint: 10 },
  { title: "Sugarcane", waterFootprint: 1.5 },
  { title: "Maize", waterFootprint: 1.222 },
  { title: "Soybeans", waterFootprint: 2.145 },
  { title: "Barley", waterFootprint: 1.3 },
  { title: "Oats", waterFootprint: 2.373 },
  { title: "Rye", waterFootprint: 1.189 },
  { title: "Millet", waterFootprint: 2.5 },
  { title: "Lentils", waterFootprint: 0.5 },
  { title: "Peas", waterFootprint: 0.6 },
  { title: "Chickpeas", waterFootprint: 0.9 },
  { title: "Groundnuts", waterFootprint: 1.5 },
  { title: "Sunflower seeds", waterFootprint: 1.8 },
  { title: "Sesame seeds", waterFootprint: 2.5 },
  { title: "Rapeseed", waterFootprint: 1.4 },
  { title: "Mustard seeds", waterFootprint: 1.3 },
  { title: "Coconuts", waterFootprint: 1.9 },
  { title: "Cashews", waterFootprint: 2.3 },
  { title: "Almonds", waterFootprint: 3.2 },
  { title: "Walnuts", waterFootprint: 3.1 },
  { title: "Pistachios", waterFootprint: 2.7 },
  { title: "Hazelnuts", waterFootprint: 2.2 },
  { title: "Pecans", waterFootprint: 2.8 },
  { title: "Brazil nuts", waterFootprint: 2.5 },
  { title: "Macadamia nuts", waterFootprint: 2.9 },
  { title: "Pine nuts", waterFootprint: 2.3 },
  { title: "Chestnuts", waterFootprint: 1.8 },
  { title: "Tea", waterFootprint: 0.9 },
  { title: "Cocoa", waterFootprint: 2.7 },
  { title: "Vanilla", waterFootprint: 1.3 },
  { title: "Cinnamon", waterFootprint: 1.1 },
  { title: "Cardamom", waterFootprint: 1.5 },
  { title: "Cloves", waterFootprint: 1.2 },
  { title: "Nutmeg", waterFootprint: 1.4 },
  { title: "Saffron", waterFootprint: 1.1 },
  { title: "Turmeric", waterFootprint: 1.3 },
  { title: "Ginger", waterFootprint: 1.2 },
  { title: "Garlic", waterFootprint: 1.1 },
  { title: "Onions", waterFootprint: 0.9 },
  { title: "Potatoes", waterFootprint: 0.5 },
  { title: "Cucumbers", waterFootprint: 0.4 },
  { title: "Eggplants", waterfootprint: 0.7 },
  { title: "Carrots", waterfootprint: 0.6 },
  { title: "Spinach", waterfootprint: 0.3 },
  { title: "Peppers", waterfootprint: 0.3 },
  { title: "Cabbage", waterfootprint: 0.2 },
  { title: "Broccoli", waterfootprint: 0.4 },
  { title: "Cauliflower", waterfootprint: 0.3 },
  { title: "Zucchini", waterfootprint: 0.2 },
  { title: "Pumpkin", waterfootprint: 0.3 },
  { title: "Squash", waterfootprint: 0.3 },
  { title: "Okra", waterfootprint: 0.3 },
  { title: "Green beans", waterfootprint: 0.3 },
];
export default items;
